config/routes.rb
Pledgeforpaul::Application.routes.draw do
  get "candidate/:slug" => "candidate#show", :as => :view_candidate

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "invite/create"

  get "invite/show"

  get "pledge/new"

  match "candidate/:slug/pledge/new" => "pledge#new", :as => :pledge_new

  match "candidate/:slug/pledge/create" => "pledge#create", :as => :pledge_create

  get "pledge/edit"

  get "pledge/update"

  get "pledge/:token" => 'pledge#show', :as => :pledge_show

  post "invite/create"

  get "invite/:token" => 'invite#show', :as => :invite_show

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

  get "portal/index"

  get "sponsor" => "portal#sponsor"
  get "contact" => "portal#contact"

  root :to => 'portal#index'

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :pledge_topic
  has_many :invites, foreign_key: 'invite_pledge_id'
  belongs_to :accepted_invite, foreign_key: :accepted_invite_id, class_name: 'Invite'

  validates_uniqueness_of :user_id, message: 'You have already pledged with this account!'
end

app/controllers/pledge_controller.rb
class PledgeController < ApplicationController
  before_filter :authenticate_user!, :except => :show

  def new
    @candidate = current_candidate
  end

  def create
    @pledge = nil
    target = nil

    #check if we have a related pledge
    if !session[PLEDGE_TOKEN_KEY].nil? and !session[PLEDGE_TOKEN_KEY].empty?
      logger.info("found related pledge token: #{session[PLEDGE_TOKEN_KEY]} when creating pledge for: #{current_user.id}")
      #we are going to create a new pledge and a JIT invite object for this new pledge.
      invite_pledge = Pledge.find_by_token(session[PLEDGE_TOKEN_KEY])

      invite = invite_pledge.invites.build({ accepted: true, user: current_user, token: Devise.friendly_token })
      @pledge = invite.build_accepted_pledge({ user: current_user, token: Devise.friendly_token, pledge_topic: invite_pledge.pledge_topic })
      target = invite
    elsif !session[INVITE_TOKEN_KEY].nil? and !session[INVITE_TOKEN_KEY].empty?
      logger.info("found related invite token: #{session[INVITE_TOKEN_KEY]} when creating pledge for: #{current_user.id}")
      #we will just associate the new pledge with the existing invite.
      invite = Invite.find_by_token(session[INVITE_TOKEN_KEY])
      invite.accepted = true
      invite.user = current_user
      @pledge = invite.build_accepted_pledge({ user: current_user, token: Devise.friendly_token, pledge_topic: invite.inviting_pledge.pledge_topic })
      target = invite
    else
      candidate = current_candidate
      @pledge = Pledge.new(user: current_user, token: Devise.friendly_token, pledge_topic: candidate)
      target = @pledge
    end

    @candidate = @pledge.pledge_topic

    respond_to do |format|
      if target.save
        format.html { render action: :new }
        format.json { render json: @pledge }
      else
        format.html { redirect_to view_candidate_path(@candidate.slug), alert: target.errors.full_messages[0] }
        format.json { render json: @pledge.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    #a user has followed a pledge back to the site.

    #we either 1.) create an invite record now and track them until they sign up.
    #2.) track them sessionally and create an invite record for status upon sign up.

    pledge = Pledge.where(token: params[:token]).first

    if pledge
      session['pledge.pledge_token'] = pledge.token
      redirect_to view_candidate_path(pledge.pledge_topic.slug)
    else
      logger.error("Someone followed a pledge token into the site that didn't exist: #{params[:token]}")
      redirect_to root_path
    end
  end

  private

  def current_candidate
    Candidate.where("active = ? and slug = ?", true, params[:slug]).first
  end
end

app/helpers/pledge_helper.rb
module PledgeHelper
end

app/views/pledge/new.html.erb
<%= content_for :page_title do %>Pledge Politics :: Pledge a Vote For <%= @candidate.name %><% end %>

<%= content_for :head do  %>
    <%= javascript_include_tag 'ZeroClipboard' %>
    <%= javascript_include_tag 'pledge' %>
<% end %>

<% if @pledge %>
<script type="text/javascript">
    $(document).ready(function(){
        $.initializePledge('<%= @pledge.token %>', '<%= @pledge.id %>');
    });
</script>
<% end %>

<div class="highlight">
    <h1>Make Your Pledge!</h1>
   <p>

     
    <a class="button" href="<%= pledge_create_path(@candidate.slug) %>" id="pledge-button">
      Click To Pledge! <%=  image_tag 'ajax-loader.gif', id: 'pledge-spinner', style: 'display: none;' %>
    </a>
  </p>

  <div id="like-actions">
    <p>Like your pledge with facebook, twitter or google+ to tell others about your pledge to vote for <%= @candidate.name %>!</p>
    <div id="fb-root" style="float: left;"></div>
    <div class="pp-all-wrap">
      <div class='pp-like-wrap'><div id="google-plus-button" class="g-plusone" data-size="medium" data-annotation="none" data-href="<%= root_path %>" style="padding-top: 5px;"></div></div>
      <div class='pp-like-wrap'><a id="twitter-button" href="https://twitter.com/intent/tweet?button_hashtag=<%= @candidate.hash_tag %>&text=<%= tweet_text(@candidate) %>" class="twitter-hashtag-button" data-url="<%= root_path %>">Tweet #<%= @candidate.hash_tag %></a></div>
      <div  class='pp-like-wrap'><div class="fb-like" data-href="<%= root_path %>" data-send="false" data-width="75" data-show-faces="false" data-font="arial" data-layout="button_count"></div></div>
      <div style="clear: both;"></div>
    </div>
  </div>
    <hr />
</div>
<div id='pledge-actions' class="middle-wrap disabled-section">
    <h2>Invite A Friend To Pledge!</h2>
    <p>
      Invite others to pledge a vote for <%= @candidate.name %> along side you and together you can make a difference!
    </p>
    Send this pledge with facebook: <div class="fb-send" data-href="<%= root_path %>" data-font="arial"></div>
    <p> - or - </p>

        <%= form_for( Invite.new, as: :invite, url: invite_create_path, remote: true, method: :post ) do |f| %>
            <%= f.hidden_field :invite_pledge_id %>
        <p>
          <%=  f.label :email %>: <%= f.text_field :email, disabled: 'disabled' %> <%=  f.submit 'Invite Someone To Pledge!', disabled: true, id: 'invite_submit' %>
        </p>

        <% end %>
    <hr />

<h2>Share Your Pledge!</h2>

  <p>Send this link to anyone and they will know you pledged a vote for <%= @candidate.name %>!</p>
  <div>
    <label>Your Pledge Link: </label><input id="pledge-direct-link" type='text' value='' readonly="readonly" disabled="disabled" />
    <div id="d_clip_container" style="position:relative">
        <p>
            <%= link_to 'Copy To Clipboard', '#', id: 'd_clip_button', class: 'button', style: 'font-size: 14pt;' %>
        </p>
    </div>
  </div>
</div>