config/routes.rb
Pledgeforpaul::Application.routes.draw do
  get "candidate/:slug" => "candidate#show", :as => :view_candidate

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "invite/create"

  get "invite/show"

  get "pledge/new"

  match "candidate/:slug/pledge/new" => "pledge#new", :as => :pledge_new

  match "candidate/:slug/pledge/create" => "pledge#create", :as => :pledge_create

  get "pledge/edit"

  get "pledge/update"

  get "pledge/:token" => 'pledge#show', :as => :pledge_show

  post "invite/create"

  get "invite/:token" => 'invite#show', :as => :invite_show

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

  get "portal/index"

  get "sponsor" => "portal#sponsor"
  get "contact" => "portal#contact"

  root :to => 'portal#index'

end

app/models/candidate.rb
class Candidate < PledgeTopic
  def self.active_candidates_by_name
    Candidate.find_all_by_active(true)
  end
end

app/controllers/candidate_controller.rb
class CandidateController < ApplicationController
  def show
    @candidate = Candidate.find_by_slug(params[:slug])

    if @candidate.nil? or not @candidate.active?
      redirect_to root_path
    else
      #store candidate id in session
      session["user_return_to"] = pledge_new_path(@candidate.slug)

      #TODO these need to be within the context of a candidate
      @total_pledge_count = @candidate.pledge_count
      @total_accepted = @candidate.accepted_invites_count
    end
  end
end

app/helpers/candidate_helper.rb
module CandidateHelper
end

app/views/candidate/show.html.erb
<%= content_for :page_title do %>Pledge Politics :: Pledge a Vote For <%= @candidate.name %><% end %>

<% content_for :head do %>
    <meta property="og:title" content="Pledge For <%= @candidate.name %>" />
    <meta property="og:type" content="politician" />
    <meta property="og:url" content="<%= root_url %>" />
    <meta property="og:image" content="http://c306571.r71.cf1.rackcdn.com/logo.jpg" />
    <meta property="og:site_name" content="Pledge For <%= @candidate.name %> - Pledge Politics" />
    <meta property="fb:app_id" content="192527500854208" />


    <!-- Add the following three tags inside head -->
    <meta itemprop="name" content="Pledge For <%= @candidate.name %>">
    <meta itemprop="description" content="Pledge For <%= @candidate.name %> - Pledge Politics.  Pledge a vote for <%= @candidate.name %>.">
    <meta itemprop="image" content="http://c306571.r71.cf1.rackcdn.com/logo.jpg">

    <script type="text/javascript">
      $(document).ready(function(){
        //facebook init
          (function(d, s, id) {
           var js, fjs = d.getElementsByTagName(s)[0];
           if (d.getElementById(id)) return;
           js = d.createElement(s); js.id = id;
           js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=192527500854208";
           fjs.parentNode.insertBefore(js, fjs);
         }(document, 'script', 'facebook-jssdk'));

       //googleplus init
       gapi.plusone.go();

      //twitter init
      !function(d,s,id){
          var js,fjs=d.getElementsByTagName(s)[0];
          if(!d.getElementById(id)){
              js=d.createElement(s);
              js.id=id;
              js.src="//platform.twitter.com/widgets.js";
              fjs.parentNode.insertBefore(js,fjs);
          }
      }(document,"script","twitter-wjs");

      });
    </script>
<% end %>

<div class="highlight">
    <h1>Pledge A Vote For <%= @candidate.name %>!</h1>
    
  <% if is_referral? %>
    <h2>A friend has invited to join the Pledge to Vote For <%= @candidate.name %>!</h2>
  <% end %>
  
    <div>
      <%= image_tag @candidate.profile_image.url(:medium) %>
    </div>

    <p id='total-vote-count'><%= @total_pledge_count %> people have pledged to make a difference.</p>

    <p id='total-accepted-count'><%=  @total_accepted %> pledge invitations have been accepted.</p>

    <%= link_to 'Vote!', pledge_create_path(@candidate.slug), class: 'button' %>
    <hr />
</div>

<div class='middle-wrap'>
  <div id="fb-root" style="float: left;"></div>
        <div class="pp-all-wrap">
          <div class='pp-like-wrap'><div id="google-plus-button" class="g-plusone" data-size="medium" data-annotation="none" data-href="<%= root_url %>" style="padding-top: 5px;"></div></div>
          <div  class='pp-like-wrap'><div class="fb-like" data-href="<%= root_url %>" data-send="true" data-width="75" data-show-faces="false" data-font="arial" data-layout="button_count"></div></div>
          <div class='pp-like-wrap'><a href="https://twitter.com/share" class="twitter-share-button" data-text="Pledge a Vote for <%= @candidate.name %>!" data-url="<%= view_candidate_url(@candidate.slug) %>" data-hashtags="<%= @candidate.hash_tag %>">Tweet</a></div>
          <div style="clear: both;"></div>
        </div>
    <h2>How Does It Work?</h2>

    <p class='center-paragraph'>
      We've consistently heard people express the feeling that their vote for a non-establishment candidate will be a waste
      of a vote, so we invite people to send out a pledge invitation to have someone join them and make their vote stronger.
      Together we can make a difference!
    </p>

    <p class="center-paragraph">
      Along with inviting someone to pledge, you will also be able to share your pledge on facebook!
    </p>

  <% if not user_signed_in? %>
    <hr />

    <h2>Get Started!</h2>
    <p style="vertical-align: middle;">Login with: <%= link_to image_tag('facebook.png', style: 'vertical-align: middle;'), user_omniauth_authorize_path(:facebook) %>  <%= link_to image_tag('twitter.png', style: 'vertical-align: middle;'), user_omniauth_authorize_path(:twitter) %> <%= link_to image_tag('openid.png', style: 'vertical-align: middle;'), user_omniauth_authorize_path(:google) %></p>
    <p>- or -</p>
    <p>
      <%= link_to 'Sign Up!', new_user_registration_path, class: 'button' %>
    </p>
  <% end %>
</div>