config/routes.rb
Pledgeforpaul::Application.routes.draw do
  get "candidate/:slug" => "candidate#show", :as => :view_candidate

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "invite/create"

  get "invite/show"

  get "pledge/new"

  match "candidate/:slug/pledge/new" => "pledge#new", :as => :pledge_new

  match "candidate/:slug/pledge/create" => "pledge#create", :as => :pledge_create

  get "pledge/edit"

  get "pledge/update"

  get "pledge/:token" => 'pledge#show', :as => :pledge_show

  post "invite/create"

  get "invite/:token" => 'invite#show', :as => :invite_show

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }

  get "portal/index"

  get "sponsor" => "portal#sponsor"
  get "contact" => "portal#contact"

  root :to => 'portal#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html itemscope itemtype="http://schema.org/Person">
<head>
  <title><%= content_for?(:page_title) ? yield(:page_title) : "Pledge Politics :: Your Source For Up To The Minute Polling" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="https://apis.google.com/js/plusone.js">
        {parsetags: 'explicit'}
  </script>
  <%= csrf_meta_tags %>
  <%= content_for :head  %>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-29684120-2']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

    <% if alert %>
        $(document).ready(function(){
            $.fn.flashError('<%= alert %>');
        });
    <% end %>

    <% if notice %>
        $(document).ready(function(){
            $.fn.flashSuccess('<%= notice %>');
        });
    <% end %>

  </script>
</head>
<body id="<%= "#{controller_name}_#{action_name}" %>">
<div id="success-holder" class="success hidden"><%= notice %></div>
<div id="error-holder" class="alert hidden"><%= alert %></div>
<div class="nav-bar-wrap"><div class="nav-bar"> | <%= link_to 'Home', root_path %> | <% active_candidates_by_name.each do |c| %> <%= link_to c.name, view_candidate_path(c.slug) %> |  <% end %></div></div>
<%= yield %>

<footer>
  <div>&copy; 2012 Spitfire Inc.</div>
  <div><%#= link_to 'Security', '#' %>
  <%= link_to 'Sponsor Campaign', sponsor_path %>
  <%#= link_to 'Advertise', '#' %>
  <%= link_to 'Contact Us', contact_path %></div>
  <%=  link_to 'Sign Out', destroy_user_session_path, method: :delete %>
</footer>
</body>
</html>